import jsPDF from 'jspdf';
import type { SlideContent } from '@/lib/document-parser';
import type { BulkAnalysisResult, ComparisonReport } from '@/types/bulk-analysis';

const PITCHGAUGE_FOOTER = "Generated by PitchGauge — pitchgauge.lovable.app";

const addPitchGaugeFooter = (pdf: jsPDF) => {
  const pageCount = (pdf as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'italic');
    pdf.setTextColor(140, 140, 140);
    const pageHeight = pdf.internal.pageSize.getHeight();
    const pageWidth = pdf.internal.pageSize.getWidth();
    pdf.text(PITCHGAUGE_FOOTER, pageWidth / 2, pageHeight - 10, { align: 'center' });
    pdf.text(`Page ${i} of ${pageCount}`, pageWidth - 20, pageHeight - 10, { align: 'right' });
    pdf.setTextColor(0, 0, 0);
  }
};

interface ScoreItem {
  score: number;
  reasoning: string;
  detailedExplanation?: string;
}

interface AnalysisResult {
  memo: string | Record<string, string>;
  scorecard: {
    team: ScoreItem;
    marketSize: ScoreItem;
    traction: ScoreItem;
    productDifferentiation: ScoreItem;
    businessModel: ScoreItem;
    competitiveLandscape: ScoreItem;
  };
  redFlags?: Array<{ severity: string; issue: string; explanation: string }>;
  followUpQuestions?: Record<string, string[]>;
  investmentThesis?: { bullCase: string; bearCase: string };
  benchmarking?: {
    overallPercentile: string;
    stageContext: string;
    comparisonNotes: string;
  };
  startupName?: string;
}

interface ComparisonData {
  startupNames: string[];
  analyses: AnalysisResult[];
  comparisonInsights?: {
    rankings: Array<{ startupName: string; rank: number; reasoning: string }>;
    comparativeInsights: {
      strengths: Record<string, string>;
      weaknesses: Record<string, string>;
      relativePerspective: string;
    };
    investmentRecommendation: string;
  };
}

export const exportAnalysisToPDF = (analysis: AnalysisResult, startupName: string) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = 20;

  const addText = (text: string, fontSize: number = 10, isBold: boolean = false) => {
    if (yPosition > 270) {
      pdf.addPage();
      yPosition = 20;
    }
    pdf.setFontSize(fontSize);
    pdf.setFont('helvetica', isBold ? 'bold' : 'normal');
    const lines = pdf.splitTextToSize(text, pageWidth - 2 * margin);
    pdf.text(lines, margin, yPosition);
    yPosition += lines.length * fontSize * 0.5 + 5;
  };

  const addSection = (title: string, content: string) => {
    addText(title, 14, true);
    addText(content, 10, false);
    yPosition += 5;
  };

  // Header
  addText(`Startup Analysis: ${startupName}`, 18, true);
  addText(`Generated: ${new Date().toLocaleDateString()}`, 10, false);
  yPosition += 10;

  // Executive Summary
  addSection('Executive Summary', 
    typeof analysis.memo === 'string' 
      ? analysis.memo 
      : Object.entries(analysis.memo).map(([k, v]) => `${k}: ${v}`).join('\n\n')
  );

  // Scorecard
  addText('Scorecard Analysis', 16, true);
  yPosition += 5;

  const categories = {
    team: 'Team',
    marketSize: 'Market Size',
    traction: 'Traction',
    productDifferentiation: 'Product Differentiation',
    businessModel: 'Business Model',
    competitiveLandscape: 'Competitive Landscape'
  };

  Object.entries(categories).forEach(([key, label]) => {
    const item = analysis.scorecard[key as keyof typeof analysis.scorecard];
    addText(`${label}: ${item.score}/10`, 12, true);
    addText(`Reasoning: ${item.reasoning}`, 10, false);
    if (item.detailedExplanation) {
      addText(`Details: ${item.detailedExplanation}`, 10, false);
    }
    yPosition += 3;
  });

  // Red Flags
  if (analysis.redFlags && analysis.redFlags.length > 0) {
    addText('Red Flags', 16, true);
    analysis.redFlags.forEach((flag, idx) => {
      addText(`${idx + 1}. [${flag.severity.toUpperCase()}] ${flag.issue}`, 11, true);
      addText(flag.explanation, 10, false);
    });
  }

  // Follow-up Questions
  if (analysis.followUpQuestions) {
    addText('Follow-up Questions', 16, true);
    Object.entries(analysis.followUpQuestions).forEach(([category, questions]) => {
      if (Array.isArray(questions)) {
        addText(`${category.charAt(0).toUpperCase() + category.slice(1)}:`, 11, true);
        questions.forEach((q, idx) => {
          addText(`${idx + 1}. ${q}`, 10, false);
        });
      }
    });
  }

  // Investment Thesis
  if (analysis.investmentThesis) {
    addSection('Bull Case', analysis.investmentThesis.bullCase);
    addSection('Bear Case', analysis.investmentThesis.bearCase);
  }

  // Benchmarking
  if (analysis.benchmarking) {
    addText('Benchmarking', 16, true);
    addText(`Overall Percentile: ${analysis.benchmarking.overallPercentile}`, 11, true);
    addText(`Stage: ${analysis.benchmarking.stageContext}`, 10, false);
    addText(analysis.benchmarking.comparisonNotes, 10, false);
    yPosition += 5;
  }

  addPitchGaugeFooter(pdf);
  pdf.save(`${startupName.replace(/\s+/g, '_')}_Analysis_${Date.now()}.pdf`);
};

export const exportComparisonToPDF = (comparisonData: ComparisonData) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = 20;

  const addText = (text: string, fontSize: number = 10, isBold: boolean = false) => {
    if (yPosition > 270) {
      pdf.addPage();
      yPosition = 20;
    }
    pdf.setFontSize(fontSize);
    pdf.setFont('helvetica', isBold ? 'bold' : 'normal');
    const lines = pdf.splitTextToSize(text, pageWidth - 2 * margin);
    pdf.text(lines, margin, yPosition);
    yPosition += lines.length * fontSize * 0.5 + 5;
  };

  // Header
  addText(`Startup Comparison Analysis`, 18, true);
  addText(`Comparing: ${comparisonData.startupNames.join(' vs ')}`, 12, false);
  addText(`Generated: ${new Date().toLocaleDateString()}`, 10, false);
  yPosition += 10;

  // Rankings
  if (comparisonData.comparisonInsights?.rankings) {
    addText('Investment Rankings', 16, true);
    comparisonData.comparisonInsights.rankings.forEach((ranking) => {
      addText(`#${ranking.rank}: ${ranking.startupName}`, 12, true);
      addText(ranking.reasoning, 10, false);
      yPosition += 3;
    });
  }

  // Comparative Insights
  if (comparisonData.comparisonInsights?.comparativeInsights) {
    const insights = comparisonData.comparisonInsights.comparativeInsights;
    
    addText('Relative Perspective', 14, true);
    addText(insights.relativePerspective, 10, false);
    yPosition += 5;

    addText('Strengths by Startup', 14, true);
    Object.entries(insights.strengths).forEach(([startup, strength]) => {
      addText(`${startup}:`, 11, true);
      addText(strength, 10, false);
    });
    yPosition += 5;

    addText('Weaknesses by Startup', 14, true);
    Object.entries(insights.weaknesses).forEach(([startup, weakness]) => {
      addText(`${startup}:`, 11, true);
      addText(weakness, 10, false);
    });
  }

  // Investment Recommendation
  if (comparisonData.comparisonInsights?.investmentRecommendation) {
    yPosition += 5;
    addText('Investment Recommendation', 16, true);
    addText(comparisonData.comparisonInsights.investmentRecommendation, 10, false);
  }

  // Individual Analyses Summary
  pdf.addPage();
  yPosition = 20;
  addText('Individual Analysis Summaries', 16, true);
  
  comparisonData.analyses.forEach((analysis, idx) => {
    const name = comparisonData.startupNames[idx] || `Startup ${idx + 1}`;
    addText(name, 14, true);
    
    // Scores - handle both scorecard formats
    const scorecard = analysis.scorecard as any;
    const scoreValues = [
      scorecard.team?.score || 0,
      scorecard.marketSize?.score || 0,
      scorecard.product?.score || scorecard.productDifferentiation?.score || 0,
      scorecard.traction?.score || 0,
      scorecard.businessModel?.score || 0,
      scorecard.defensibility?.score || scorecard.competitiveLandscape?.score || 0,
    ];
    
    const avgScore = scoreValues.reduce((a, b) => a + b, 0) / scoreValues.length;
    
    addText(`Average Score: ${avgScore.toFixed(1)}/10`, 11, false);
    
    if (analysis.redFlags && analysis.redFlags.length > 0) {
      addText(`Red Flags: ${analysis.redFlags.length}`, 11, false);
    }
    yPosition += 5;
  });

  addPitchGaugeFooter(pdf);
  pdf.save(`Comparison_${comparisonData.startupNames.join('_vs_')}_${Date.now()}.pdf`);
};

export const exportPitchSummaryToPDF = (
  pitchSummary: string, 
  slides?: SlideContent[], 
  startupName?: string
) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = 20;

  const addText = (text: string, fontSize: number = 10, isBold: boolean = false) => {
    if (yPosition > 270) {
      pdf.addPage();
      yPosition = 20;
    }
    pdf.setFontSize(fontSize);
    pdf.setFont('helvetica', isBold ? 'bold' : 'normal');
    const lines = pdf.splitTextToSize(text, pageWidth - 2 * margin);
    pdf.text(lines, margin, yPosition);
    yPosition += lines.length * fontSize * 0.5 + 5;
  };

  const addSection = (title: string, content: string) => {
    addText(title, 14, true);
    addText(content, 10, false);
    yPosition += 5;
  };

  // Header
  const title = startupName 
    ? `Extracted Pitch Summary: ${startupName}` 
    : 'Extracted Pitch Summary';
  addText(title, 18, true);
  addText(`Generated: ${new Date().toLocaleDateString()}`, 10, false);
  yPosition += 10;

  // Executive Summary
  addSection('Executive Summary', pitchSummary);

  // Slide-by-slide breakdown
  if (slides && slides.length > 0) {
    yPosition += 5;
    addText('Slide-by-Slide Breakdown', 16, true);
    yPosition += 5;

    slides.forEach((slide) => {
      if (yPosition > 250) {
        pdf.addPage();
        yPosition = 20;
      }
      
      const slideTitle = slide.heading 
        ? `Slide ${slide.slideNumber}: ${slide.heading}`
        : `Slide ${slide.slideNumber}`;
      addText(slideTitle, 12, true);
      addText(slide.content, 10, false);
      yPosition += 3;
    });
  }

  // Save PDF
  addPitchGaugeFooter(pdf);
  const fileName = startupName 
    ? `${startupName.replace(/\s+/g, '_')}_Pitch_Summary_${Date.now()}.pdf`
    : `Pitch_Summary_${Date.now()}.pdf`;
  pdf.save(fileName);
};

export const exportBulkAnalysisToPDF = (
  results: BulkAnalysisResult[],
  comparisonReport: ComparisonReport | null,
  batchName: string
) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = 20;

  const addText = (text: string, fontSize: number = 10, isBold: boolean = false) => {
    if (yPosition > 270) {
      pdf.addPage();
      yPosition = 20;
    }
    pdf.setFontSize(fontSize);
    pdf.setFont('helvetica', isBold ? 'bold' : 'normal');
    const lines = pdf.splitTextToSize(text, pageWidth - 2 * margin);
    pdf.text(lines, margin, yPosition);
    yPosition += lines.length * fontSize * 0.5 + 5;
  };

  // Header
  addText('Bulk Startup Analysis Report', 18, true);
  addText(`Batch: ${batchName}`, 12, false);
  addText(`Generated: ${new Date().toLocaleDateString()}`, 10, false);
  addText(`Total Startups: ${results.length}`, 10, false);
  yPosition += 10;

  // Overall Recommendation
  if (comparisonReport?.overallRecommendation) {
    addText('Overall Recommendation', 16, true);
    addText(comparisonReport.overallRecommendation, 10, false);
    yPosition += 8;
  }

  // Investment Rankings
  if (comparisonReport?.investmentRankings) {
    addText('Investment Rankings', 16, true);
    yPosition += 3;
    comparisonReport.investmentRankings.forEach((ranking) => {
      addText(`#${ranking.rank}: ${ranking.startupName} (${ranking.overallScore}/10)`, 12, true);
      addText(`Top Strengths: ${ranking.topStrengths.join(', ')}`, 10, false);
      addText(`Recommendation: ${ranking.recommendation}`, 10, false);
      yPosition += 3;
    });
  }

  // Sector Breakdown
  if (comparisonReport?.sectorBreakdown) {
    yPosition += 5;
    addText('Sector Breakdown', 16, true);
    Object.entries(comparisonReport.sectorBreakdown).forEach(([sector, count]) => {
      addText(`${sector}: ${count} startup${count !== 1 ? 's' : ''}`, 10, false);
    });
  }

  // Strengths & Weaknesses
  if (comparisonReport?.strengthsAndWeaknesses) {
    pdf.addPage();
    yPosition = 20;
    addText('Strengths & Weaknesses', 16, true);
    yPosition += 3;
    Object.entries(comparisonReport.strengthsAndWeaknesses).forEach(([name, data]) => {
      addText(name, 12, true);
      addText(`Strengths: ${data.strengths.join('; ')}`, 10, false);
      addText(`Weaknesses: ${data.weaknesses.join('; ')}`, 10, false);
      yPosition += 3;
    });
  }

  // Individual Results
  pdf.addPage();
  yPosition = 20;
  addText('Individual Startup Scores', 16, true);
  yPosition += 5;

  const scoreLabels: Record<string, string> = {
    team: 'Team', product: 'Product', market: 'Market',
    traction: 'Traction', businessModel: 'Business Model', funding: 'Competitive Landscape'
  };
  const scoreKeys = ['team', 'product', 'market', 'traction', 'businessModel', 'funding'] as const;

  results.forEach((r) => {
    if (r.scores.overall === 0 && r.summary === 'Failed to analyze this startup') return;
    
    addText(`${r.startupName} — ${r.sector} (${r.scores.overall}/10)`, 12, true);
    addText(r.summary, 10, false);
    
    scoreKeys.forEach((key) => {
      addText(`  ${scoreLabels[key]}: ${r.scores[key]}/10 — ${r.metrics[key === 'funding' ? 'funding' : key]}`, 9, false);
    });
    yPosition += 5;
  });

  addPitchGaugeFooter(pdf);
  const fileName = `${batchName.replace(/[^a-z0-9]/gi, '_')}_report_${new Date().toISOString().split('T')[0]}.pdf`;
  pdf.save(fileName);
};

// ============================================================
// DEMO-SPECIFIC PDF EXPORTS
// ============================================================

export const exportDemoAnalysisToPDF = (analysis: AnalysisResult, startupName: string, fileName: string) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = 20;

  const addText = (text: string, fontSize: number = 10, isBold: boolean = false) => {
    if (yPosition > 270) { pdf.addPage(); yPosition = 20; }
    pdf.setFontSize(fontSize);
    pdf.setFont('helvetica', isBold ? 'bold' : 'normal');
    const lines = pdf.splitTextToSize(text, pageWidth - 2 * margin);
    pdf.text(lines, margin, yPosition);
    yPosition += lines.length * fontSize * 0.5 + 5;
  };

  const addSection = (title: string, content: string) => {
    addText(title, 14, true);
    addText(content, 10, false);
    yPosition += 5;
  };

  addText(`Startup Analysis: ${startupName}`, 18, true);
  addText(`Generated: ${new Date().toLocaleDateString()}`, 10, false);
  yPosition += 10;

  addSection('Executive Summary',
    typeof analysis.memo === 'string' ? analysis.memo : Object.entries(analysis.memo).map(([k, v]) => `${k}: ${v}`).join('\n\n')
  );

  addText('Scorecard Analysis', 16, true);
  yPosition += 5;
  const categories: Record<string, string> = {
    team: 'Team Quality', marketSize: 'Market Size', traction: 'Traction',
    productDifferentiation: 'Product Differentiation', businessModel: 'Business Model', competitiveLandscape: 'Competitive Landscape'
  };
  Object.entries(categories).forEach(([key, label]) => {
    const item = analysis.scorecard[key as keyof typeof analysis.scorecard];
    addText(`${label}: ${item.score}/10`, 12, true);
    addText(`Reasoning: ${item.reasoning}`, 10, false);
    if (item.detailedExplanation) addText(`Details: ${item.detailedExplanation}`, 10, false);
    yPosition += 3;
  });

  if (analysis.redFlags?.length) {
    addText('Red Flags', 16, true);
    analysis.redFlags.forEach((flag, idx) => {
      addText(`${idx + 1}. [${flag.severity.toUpperCase()}] ${flag.issue}`, 11, true);
      addText(flag.explanation, 10, false);
    });
  }

  if (analysis.followUpQuestions) {
    addText('Questions to Ask Founders', 16, true);
    Object.entries(analysis.followUpQuestions).forEach(([category, questions]) => {
      if (Array.isArray(questions)) {
        addText(`${category.charAt(0).toUpperCase() + category.slice(1)}:`, 11, true);
        questions.forEach((q, idx) => addText(`${idx + 1}. ${q}`, 10, false));
      }
    });
  }

  if (analysis.investmentThesis) {
    addSection('Bull Case', analysis.investmentThesis.bullCase);
    addSection('Bear Case', analysis.investmentThesis.bearCase);
  }

  if (analysis.benchmarking) {
    addText('Benchmarking', 16, true);
    addText(`Overall Percentile: ${analysis.benchmarking.overallPercentile}`, 11, true);
    addText(`Stage: ${analysis.benchmarking.stageContext}`, 10, false);
    addText(analysis.benchmarking.comparisonNotes, 10, false);
  }

  addPitchGaugeFooter(pdf);
  pdf.save(fileName);
};

export const exportDemoComparisonToPDF = (
  results: Array<{
    startupName: string;
    scorecard: Record<string, { score: number; reasoning: string }>;
    redFlags?: Array<{ severity: string; issue: string; explanation: string }>;
  }>,
  insights: {
    rankings: Array<{ rank: number; name: string; overallScore: number; topStrengths: string[] }>;
    overallRecommendation: string;
    strengthsWeaknesses: Record<string, { strengths: string[]; weaknesses: string[] }>;
  }
) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = 20;

  const addText = (text: string, fontSize: number = 10, isBold: boolean = false) => {
    if (yPosition > 270) { pdf.addPage(); yPosition = 20; }
    pdf.setFontSize(fontSize);
    pdf.setFont('helvetica', isBold ? 'bold' : 'normal');
    const lines = pdf.splitTextToSize(text, pageWidth - 2 * margin);
    pdf.text(lines, margin, yPosition);
    yPosition += lines.length * fontSize * 0.5 + 5;
  };

  addText('Startup Comparison Report', 18, true);
  addText(`Generated: ${new Date().toLocaleDateString()}`, 10, false);
  yPosition += 10;

  addText('Investment Rankings', 16, true);
  insights.rankings.forEach((r) => {
    addText(`#${r.rank}: ${r.name} — ${r.overallScore}/10`, 12, true);
    addText(`Top Strengths: ${r.topStrengths.join(', ')}`, 10, false);
    yPosition += 3;
  });

  yPosition += 5;
  const scorecardLabels: Record<string, string> = {
    team: 'Team', marketSize: 'Market Size', productDifferentiation: 'Product',
    traction: 'Traction', businessModel: 'Business Model', competitiveLandscape: 'Competition'
  };

  results.forEach((r) => {
    addText(`${r.startupName} — Detailed Scores`, 14, true);
    Object.entries(scorecardLabels).forEach(([key, label]) => {
      const entry = r.scorecard[key];
      if (entry) {
        addText(`${label}: ${entry.score}/10 — ${entry.reasoning}`, 10, false);
      }
    });
    yPosition += 5;
  });

  addText('Strengths & Weaknesses', 16, true);
  Object.entries(insights.strengthsWeaknesses).forEach(([name, sw]) => {
    addText(name, 12, true);
    addText(`Strengths: ${sw.strengths.join('; ')}`, 10, false);
    addText(`Weaknesses: ${sw.weaknesses.join('; ')}`, 10, false);
    yPosition += 3;
  });

  yPosition += 5;
  addText('Overall Recommendation', 16, true);
  addText(insights.overallRecommendation, 10, false);

  addPitchGaugeFooter(pdf);
  pdf.save('PitchScore_Comparison_Demo.pdf');
};

export const exportDemoBulkToPDF = (
  results: BulkAnalysisResult[],
  comparisonReport: ComparisonReport | null
) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = 20;

  const addText = (text: string, fontSize: number = 10, isBold: boolean = false) => {
    if (yPosition > 270) { pdf.addPage(); yPosition = 20; }
    pdf.setFontSize(fontSize);
    pdf.setFont('helvetica', isBold ? 'bold' : 'normal');
    const lines = pdf.splitTextToSize(text, pageWidth - 2 * margin);
    pdf.text(lines, margin, yPosition);
    yPosition += lines.length * fontSize * 0.5 + 5;
  };

  addText('Bulk Startup Analysis Report', 18, true);
  addText(`Total Startups: ${results.length}`, 10, false);
  addText(`Generated: ${new Date().toLocaleDateString()}`, 10, false);
  yPosition += 10;

  if (comparisonReport?.overallRecommendation) {
    addText('Overall Recommendation', 16, true);
    addText(comparisonReport.overallRecommendation, 10, false);
    yPosition += 8;
  }

  if (comparisonReport?.investmentRankings) {
    addText('Investment Rankings', 16, true);
    comparisonReport.investmentRankings.forEach((r) => {
      addText(`#${r.rank}: ${r.startupName} (${r.overallScore}/10)`, 12, true);
      addText(`Strengths: ${r.topStrengths.join(', ')}`, 10, false);
      addText(`Recommendation: ${r.recommendation}`, 10, false);
      yPosition += 3;
    });
  }

  if (comparisonReport?.sectorBreakdown) {
    yPosition += 5;
    addText('Sector Distribution', 16, true);
    Object.entries(comparisonReport.sectorBreakdown).forEach(([sector, count]) => {
      addText(`${sector}: ${count} startup${count !== 1 ? 's' : ''}`, 10, false);
    });
  }

  addPitchGaugeFooter(pdf);
  pdf.save('PitchGauge_Bulk_Demo.pdf');
};
