project_id = "rxppdvnzcnfnbpjyscti"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.analyze-startup]
verify_jwt = false

[functions.compare-startups]
verify_jwt = false

[functions.analyze-bulk-startups]
verify_jwt = false

[functions.generate-bulk-comparison]
verify_jwt = false

[functions.parse-pdf]
verify_jwt = false
