import { usePageMeta } from "@/hooks/usePageMeta";
import { Link } from "react-router-dom";

export default function Terms() {
  usePageMeta("Terms & Privacy — PitchGauge", "PitchGauge Terms of Service and Privacy Policy.");

  return (
    <div className="min-h-screen bg-background py-16 px-4">
      <div className="max-w-3xl mx-auto prose prose-neutral dark:prose-invert">

        <h1 className="text-3xl font-bold text-foreground mb-2">Terms of Service &amp; Privacy Policy</h1>
        <p className="text-muted-foreground text-sm mb-10">PitchGauge — Last updated: August 2026</p>

        <hr className="my-8 border-border" />

        {/* TERMS OF SERVICE */}
        <h2 className="text-2xl font-semibold text-foreground mt-10 mb-4">Terms of Service</h2>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">1. Acceptance of Terms</h3>
        <p className="text-muted-foreground leading-relaxed">By creating an account or using PitchGauge ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">2. Description of Service</h3>
        <p className="text-muted-foreground leading-relaxed">PitchGauge is an AI-powered pitch deck evaluation tool currently operating as a <strong>beta product</strong>. The Service analyses pitch content and generates structured feedback using large language models.</p>
        <p className="text-muted-foreground leading-relaxed mt-2">The Service is provided on an "as is" and "as available" basis. We make no guarantees about uptime, availability, or continuity of the Service, and features may change or be removed at any time without notice.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">3. Not Investment Advice</h3>
        <p className="text-muted-foreground leading-relaxed">All output generated by PitchGauge — including scores, analysis, red flags, and follow-up questions — is for <strong>informational purposes only</strong> and does not constitute financial, investment, or legal advice. You should not rely on the Service to make investment decisions. We accept no liability for decisions made on the basis of PitchGauge output.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">4. Eligibility</h3>
        <p className="text-muted-foreground leading-relaxed">You must be at least 18 years old to use the Service. By using PitchGauge, you represent that you meet this requirement.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">5. Your Account</h3>
        <p className="text-muted-foreground leading-relaxed">You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. Notify us immediately via our <Link to="/contact" className="text-primary hover:underline">contact form</Link> if you suspect unauthorised access.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">6. Acceptable Use</h3>
        <p className="text-muted-foreground leading-relaxed">You agree not to:</p>
        <ul className="text-muted-foreground list-disc pl-6 space-y-1 mt-2">
          <li>Upload content that is unlawful, defamatory, or infringes third-party intellectual property rights</li>
          <li>Attempt to reverse-engineer, scrape, or otherwise extract data from the Service in bulk</li>
          <li>Use the Service to train competing AI models</li>
          <li>Circumvent any access controls or rate limits</li>
        </ul>
        <p className="text-muted-foreground leading-relaxed mt-2">We reserve the right to suspend or terminate accounts that violate these terms.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">7. Payments and Refunds</h3>
        <p className="text-muted-foreground leading-relaxed">Paid plans are billed through Stripe. <strong>All payments are non-refundable</strong> unless required by applicable law. You may cancel your subscription at any time; cancellation takes effect at the end of the current billing period, and you will retain access until that date.</p>
        <p className="text-muted-foreground leading-relaxed mt-2">We reserve the right to change pricing at any time. We will provide reasonable notice of price changes before they take effect.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">8. Intellectual Property</h3>
        <p className="text-muted-foreground leading-relaxed">You retain ownership of all pitch content you upload to the Service. By uploading content, you grant us a limited licence to process that content solely for the purpose of providing the Service to you.</p>
        <p className="text-muted-foreground leading-relaxed mt-2">We retain all rights in the PitchGauge platform, interface, and underlying models.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">9. Limitation of Liability</h3>
        <p className="text-muted-foreground leading-relaxed">To the maximum extent permitted by law, PitchGauge and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including loss of data, loss of profits, or business interruption.</p>
        <p className="text-muted-foreground leading-relaxed mt-2">Our total liability to you for any claim arising from use of the Service shall not exceed the amount you paid us in the 30 days preceding the claim.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">10. Changes to These Terms</h3>
        <p className="text-muted-foreground leading-relaxed">We may update these Terms at any time. We will notify you of material changes by email or via the Service. Continued use of the Service after changes take effect constitutes acceptance of the updated Terms.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">11. Governing Law</h3>
        <p className="text-muted-foreground leading-relaxed">These Terms are governed by the laws of <strong>England and Wales</strong>. Any disputes shall be subject to the exclusive jurisdiction of the courts of <strong>England and Wales</strong>.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">12. Contact</h3>
        <p className="text-muted-foreground leading-relaxed">For questions about these Terms, use our <Link to="/contact" className="text-primary hover:underline">contact form</Link>.</p>

        <hr className="my-10 border-border" />

        {/* PRIVACY POLICY */}
        <h2 className="text-2xl font-semibold text-foreground mt-10 mb-4">Privacy Policy</h2>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">1. Who We Are</h3>
        <p className="text-muted-foreground leading-relaxed">PitchGauge is operated by PitchGauge. For privacy-related enquiries, use our <Link to="/contact" className="text-primary hover:underline">contact form</Link>.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">2. What Data We Collect</h3>
        <div className="overflow-x-auto mt-2">
          <table className="w-full text-sm text-muted-foreground border border-border rounded">
            <thead>
              <tr className="bg-secondary">
                <th className="text-left p-3 font-medium text-foreground">Data</th>
                <th className="text-left p-3 font-medium text-foreground">Why</th>
              </tr>
            </thead>
            <tbody>
              {[
                ["Email address", "Account creation and authentication"],
                ["Name (if provided)", "Account display"],
                ["Pitch content (text or PDF)", "To provide the evaluation service"],
                ["Usage data (feature interactions, timestamps)", "To improve the Service"],
                ["Payment information", "Processed by Stripe; we do not store card details"],
              ].map(([data, why]) => (
                <tr key={data} className="border-t border-border">
                  <td className="p-3">{data}</td>
                  <td className="p-3">{why}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">3. How We Use Your Data</h3>
        <ul className="text-muted-foreground list-disc pl-6 space-y-1 mt-2">
          <li>Provide and operate the Service</li>
          <li>Send transactional emails (account confirmation, receipts)</li>
          <li>Improve the accuracy and quality of evaluations</li>
          <li>Comply with legal obligations</li>
        </ul>
        <p className="text-muted-foreground leading-relaxed mt-2">We do not sell your data to third parties. We do not use your pitch content to train AI models.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">4. Third-Party Services</h3>
        <div className="overflow-x-auto mt-2">
          <table className="w-full text-sm text-muted-foreground border border-border rounded">
            <thead>
              <tr className="bg-secondary">
                <th className="text-left p-3 font-medium text-foreground">Provider</th>
                <th className="text-left p-3 font-medium text-foreground">Purpose</th>
                <th className="text-left p-3 font-medium text-foreground">Privacy Policy</th>
              </tr>
            </thead>
            <tbody>
              {[
                ["Supabase", "Database and authentication", "https://supabase.com/privacy", "supabase.com/privacy"],
                ["Stripe", "Payment processing", "https://stripe.com/privacy", "stripe.com/privacy"],
                ["Google (Gemini API)", "AI pitch analysis", "https://policies.google.com/privacy", "policies.google.com/privacy"],
              ].map(([provider, purpose, href, label]) => (
                <tr key={provider} className="border-t border-border">
                  <td className="p-3">{provider}</td>
                  <td className="p-3">{purpose}</td>
                  <td className="p-3"><a href={href} target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">{label}</a></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">5. Data Retention</h3>
        <p className="text-muted-foreground leading-relaxed">We retain your account data for as long as your account is active. If you delete your account, we will delete your personal data within 30 days, except where we are required to retain it for legal or financial compliance purposes.</p>
        <p className="text-muted-foreground leading-relaxed mt-2">Pitch content is retained for the duration of your account to enable features such as history and comparison. You may delete individual analyses at any time from your dashboard.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">6. Cookies</h3>
        <p className="text-muted-foreground leading-relaxed">PitchGauge uses essential cookies required for authentication and session management. We do not use tracking or advertising cookies.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">7. Your Rights</h3>
        <p className="text-muted-foreground leading-relaxed">Depending on your jurisdiction, you may have the right to access, correct, delete, or port your personal data, or to object to or restrict certain processing. To exercise any of these rights, submit a request via our <Link to="/contact" className="text-primary hover:underline">contact form</Link>. We will respond within 30 days.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">8. Security</h3>
        <p className="text-muted-foreground leading-relaxed">We use industry-standard measures to protect your data, including encrypted connections (TLS) and row-level security on our database. However, no system is entirely secure, and we cannot guarantee absolute security.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">9. Children</h3>
        <p className="text-muted-foreground leading-relaxed">The Service is not directed at children under 13. We do not knowingly collect personal data from children. If you believe a child has provided us with personal data, contact us and we will delete it.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">10. Changes to This Policy</h3>
        <p className="text-muted-foreground leading-relaxed">We may update this Privacy Policy from time to time. We will notify you of material changes by email or via the Service.</p>

        <h3 className="text-lg font-semibold text-foreground mt-6 mb-2">11. Contact</h3>
        <p className="text-muted-foreground leading-relaxed">For any privacy-related questions or requests, use our <Link to="/contact" className="text-primary hover:underline">contact form</Link>.</p>

        <div className="mt-12 pt-8 border-t border-border">
          <Link to="/" className="text-primary hover:underline text-sm">← Back to PitchGauge</Link>
        </div>

      </div>
    </div>
  );
}
