// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-analyses.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_analyses_default = defineTool({
  name: "list_analyses",
  title: "List startup analyses",
  description: "List the signed-in user's saved PitchGauge startup analyses (id, name, scorecard summary, created_at). Newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("startup_analyses").select("id, startup_name, scorecard, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { analyses: data }
    };
  }
});

// src/lib/mcp/tools/get-analysis.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_analysis_default = defineTool2({
  name: "get_analysis",
  title: "Get startup analysis",
  description: "Fetch one saved PitchGauge startup analysis by id for the signed-in user, including full memo, scorecard, red flags, and benchmarking.",
  inputSchema: {
    id: z2.string().uuid().describe("Analysis id (uuid) from list_analyses.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser2(ctx).from("startup_analyses").select("*").eq("id", id).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { analysis: data }
    };
  }
});

// src/lib/mcp/tools/get-subscription.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_subscription_default = defineTool3({
  name: "get_subscription",
  title: "Get subscription",
  description: "Return the signed-in user's current PitchGauge subscription tier and status (free, pro, scale).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser3(ctx).from("subscriptions").select("tier, status, current_period_end").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    const row = data ?? { tier: "free", status: "inactive", current_period_end: null };
    return {
      content: [{ type: "text", text: JSON.stringify(row) }],
      structuredContent: { subscription: row }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rxppdvnzcnfnbpjyscti";
var mcp_default = defineMcp({
  name: "pitchgauge",
  title: "PitchGauge",
  version: "0.1.0",
  instructions: "Read-only access to the signed-in PitchGauge user's startup analyses and subscription. Use list_analyses to browse saved analyses, get_analysis for full detail (memo, scorecard, red flags, benchmarking), and get_subscription for the current plan.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_analyses_default, get_analysis_default, get_subscription_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
